import { library } from '@fortawesome/fontawesome-svg-core'
import { faCircleNotch, faSignOutAlt, faCheck, faCheckCircle, faHeart, faCopy, faTrash, faArrowUp, faArrowDown, faChevronUp, faChevronDown, faCogs, faEye, faList, faPlus, faEllipsisV, faChevronLeft, faChevronRight, faBell, faBrain, faEdit, faDownload, faShareAlt, faUserShield } from '@fortawesome/free-solid-svg-icons'

library.add(faCircleNotch)
library.add(faSignOutAlt)
library.add(faCheckCircle)
library.add(faHeart)
library.add(faCopy)
library.add(faTrash)
library.add(faChevronUp)
library.add(faChevronDown)
library.add(faCogs)
library.add(faEye)
library.add(faList)
library.add(faPlus)
library.add(faEllipsisV)
library.add(faChevronLeft)
library.add(faChevronRight)
library.add(faBell)
library.add(faBrain)
library.add(faEdit)
library.add(faDownload)
library.add(faShareAlt)
library.add(faUserShield)